### ISSUE TITLE
PA本番環境にてデバッグモードがTrueでないとエラーがでる

### ISSUE THREAD

**Issue by takekobaya** [takekobaya/seigikou_portal_pythonanywhere#2]
CSSが関係していそう

**Comment by takekobaya** [comment]
static ファイルを1ヶ所？にまとめて、そのフォルダを参照するようにするとなおる。
https://www.mathpython.com/django-debug-false
PAからGithub にプッシュがうまくできていない。

**Comment by HRKMSM** [comment]
development.pyとproduction.pyを分けてDEBUGも適切に設定したのでこのバグ治っていると思いますがどうでしょう？

**Comment by takekobaya** [comment]
PAの本番環境で起こるバグです。開発環境では起こりません。
PAのstaticfilesにCSSファイル？を集約するとなおっています。
「fix-kobaya」のブランチに最新版をプッシュしました

**Comment by takekobaya** [comment]
https://qiita.com/saira/items/a1c565c4a2eace268a07
このページが分かりやすい

**Comment by HRKMSM** [comment]
了解です。このissueはCloseできそうですね！

**Comment by takekobaya** [comment]
開発環境のstaticフォルダと本番環境のフォルダがきちんと合わせたらクローズ。
とりあえずは運用に問題ないが、見た目を気にするときには修正した方が良い。

**Comment by takekobaya** [comment]
開発環境の静的フォルダの名前を「static」から「staticfiles」に変更することで、本番環境と統一を図った。
