### ISSUE TITLE
メンバーリストに自己紹介欄、写真欄をつくりたい

### ISSUE THREAD

**Issue by HRKMSM** [takekobaya/seigikou_portal_pythonanywhere#22]

**Comment by takekobaya** [comment]
メンバーリストに写真登録できるようにしました。
自己紹介画面は今後作ります。入力は「その他」の項目がありますが、現在表示していません。

**Comment by takekobaya** [comment]
「その他」のモデル項目を「自己紹介」として使います。
メンバーリストに表示するようにしました
