### ISSUE TITLE
イベントの日程入力をわかりやすくしたい

### ISSUE THREAD

**Issue by HRKMSM** [takekobaya/seigikou_portal_pythonanywhere#27]

**Comment by takekobaya** [comment]
入力方法は改善したが、更新する場合イベントの日程がリセットされる問題あり。

以下Chatgptに聞いた時のコメント。まだ未解決です
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
ただし、ブラウザでの<input type="date">や<input type="time">の扱いに関連して、入力フィールドの表示形式やユーザー入力の扱いに問題がある場合には、以下の点を検討することができます。

JavaScriptを使用したフォームの改善: ブラウザが期待する特定の日付や時間の形式がある場合、JavaScriptを使用してユーザー入力を制御し、適切な形式でサーバーに送信するようにすることができます。これにより、ユーザーが異なる形式で日付や時間を入力した場合でも、適切に処理することができます。

カスタムJavaScriptを用いたバリデーション: フォームが送信される前に、入力された日付や時間が正しい形式であることを確認するカスタムJavaScriptバリデーションロジックを追加することもできます。これにより、ユーザーが間違った形式でデータを入力した場合に、フォームの送信を防ぎ、適切なエラーメッセージを表示することができます。

HTMLテンプレートのカスタマイズ: {{ form.as_p }}の代わりに、各フォームフィールドを個別にレンダリングし、必要に応じて追加のHTML属性やJavaScriptイベントハンドラを直接指定することで、フォームの挙動をさらに細かく制御することができます。ただし、これにはテンプレートの複雑さが増すデメリットがあります。

現在の問題（更新入力画面で日付や時間がリセットされる）は、Django側のフォームのウィジェット設定やビューの処理に関連することが多いため、HTMLテンプレートを修正する前に、フォームの定義やビューの処理を再度確認することをお勧めします。特に、フォームウィジェットのformat属性がブラウザの期待する形式と一致しているか、また、更新時にフォームが適切なモデルインスタンスで初期化されているかを確認してください。

**Comment by takekobaya** [comment]
更新画面から再アクセスすると日付がリセットされてしまう問題は、フォームの初期値が設定されていないために起こっている可能性があります。フォームが再表示される際に、以前入力された値をフォームに再度設定することでこの問題を解決
