### ISSUE TITLE
メンバーリストの詳細を押すとトップページに飛ぶ

### ISSUE THREAD

**Issue by HRKMSM** [takekobaya/seigikou_portal_pythonanywhere#9]
メンバーの詳細更新画面にいかずトップページに飛んでしまう。
イベントリストのメンバーから詳細押した場合はメンバー更新が可能

**Comment by takekobaya** [comment]
@HRKMSM 
最新版では発生していないように思いますが。。。

**Comment by HRKMSM** [comment]
今試しましたがトップページに戻りますね。なぜだろう。。。

**Comment by HRKMSM** [comment]
青技交中国アプリ、メンバー詳細ボタンの飛び先が環境で違う？（Macではトップ画面に遷移）
小林さんしか詳細をいじれない仕様だった！?
権限いじっても詳細見れないのでバグっぽい

**Comment by takekobaya** [comment]
アクティブユーザ　サイトにログインできるメンバーは閲覧可能に変更
